@baseUrl = http://localhost:5080/peopleapi/v1
@fileName = 0f38f8a013e94cf3b750d4e018653b3e.png

### Upload an image
# Uses the test image stored next to this HTTP file.
POST {{baseUrl}}/images
Content-Type: multipart/form-data; boundary=Boundary

--Boundary
Content-Disposition: form-data; name="file"; filename="test-image.png"
Content-Type: image/png

< ./test-image.png
--Boundary--

### Read image
GET {{baseUrl}}/images/{{fileName}}

### Delete image
DELETE {{baseUrl}}/images/{{fileName}}
